In [1]:

import seaborn as sns
df = sns.load_dataset("car_crashes")
df.columns

Index(['total', 'speeding', 'alcohol', 'not_distracted', 'no_previous',
       'ins_premium', 'ins_losses', 'abbrev'],
      dtype='object')

In [71]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [20]:
#type(df.columns["age"])

index_of_age_column = df.columns.get_loc("total")
type(df.columns[index_of_age_column])

str

In [23]:
df_new = ["NUM_" + col.upper() if df[col].dtype!="O" else col.upper() for col in df.columns]

In [24]:
df_new

['NUM_TOTAL',
 'NUM_SPEEDING',
 'NUM_ALCOHOL',
 'NUM_NOT_DISTRACTED',
 'NUM_NO_PREVIOUS',
 'NUM_INS_PREMIUM',
 'NUM_INS_LOSSES',
 'ABBREV']

In [37]:

df_new_new =[col.upper() if "no" in col else col.upper()+"_FLAG" for col in df.columns ]

In [38]:
df_new_new

['TOTAL_FLAG',
 'SPEEDING_FLAG',
 'ALCOHOL_FLAG',
 'NOT_DISTRACTED',
 'NO_PREVIOUS',
 'INS_PREMIUM_FLAG',
 'INS_LOSSES_FLAG',
 'ABBREV_FLAG']

In [40]:
new_cols=['total', 'speeding', 'alcohol', 'not_distracted','ins_premium', 'ins_losses']
new_df=df[new_cols].head()

In [41]:
new_df.columns

Index(['total', 'speeding', 'alcohol', 'not_distracted', 'ins_premium',
       'ins_losses'],
      dtype='object')

### **pandas alıştırması**

In [46]:
df= sns.load_dataset("titanic")
df["sex"].value_counts()

sex
male      577
female    314
Name: count, dtype: int64

In [52]:
df.nunique()

survived         2
pclass           3
sex              2
age             88
sibsp            7
parch            7
fare           248
embarked         3
class            3
who              3
adult_male       2
deck             7
embark_town      3
alive            2
alone            2
dtype: int64

In [53]:
df["pclass"].value_counts()

pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [55]:
df[["pclass","parch"]].value_counts()

pclass  parch
3       0        381
1       0        163
2       0        134
3       1         55
        2         43
2       1         32
1       1         31
        2         21
2       2         16
3       5          5
        3          3
        4          3
2       3          2
1       4          1
3       6          1
Name: count, dtype: int64

In [63]:
df["embarked"].dtype
df["embarked"]=df["embarked"].astype("category")
df["embarked"].dtype

CategoricalDtype(categories=['C', 'Q', 'S'], ordered=False, categories_dtype=object)

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    category
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(3), float64(2), int64(4), object(4)
memory usage: 74.7+ KB

In [77]:
# Koşullu olarak 'embarked' sütunu 'C' olan satırları seçme
df[df["embarked"] == "C"].head(10)

# 'embarked' sütunu 'C' olan tüm satırları yazdırma
#print(embarked_c["embarked"])

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
19,1,3,female,NaN,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True
26,0,3,male,NaN,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,no,True
30,0,1,male,40.0,0,0,27.7208,C,First,man,True,NaN,Cherbourg,no,True
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
34,0,1,male,28.0,1,0,82.1708,C,First,man,True,NaN,Cherbourg,no,False
36,1,3,male,NaN,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,yes,True
39,1,3,female,14.0,1,0,11.2417,C,Third,child,False,NaN,Cherbourg,yes,False
42,0,3,male,NaN,0,0,7.8958,C,Third,man,True,NaN,Cherbourg,no,True

In [78]:
df[df["embarked"] != "C"].head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True

In [85]:
df[(df["age"] < 30) | (df["sex"] == "female")]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [84]:
df[(df["fare"] > 500) & (df["age"] > 70)]

Empty DataFrame
Columns: [survived, pclass, sex, age, sibsp, parch, fare, embarked, class, who, adult_male, deck, embark_town, alive, alone]
Index: []

In [86]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [87]:
df.drop("who", axis=1, inplace=True)

In [88]:
type(df["deck"].mode())

pandas.core.series.Series

In [89]:
df["deck"].mode()[0]

'C'

In [90]:
df["deck"].fillna(df["deck"].mode()[0], inplace=True)

In [91]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
adult_male       0
deck             0
embark_town      2
alive            0
alone            0
dtype: int64

In [97]:
#type(df["age"].meadian())
df["age"].median()

28.0

In [99]:
df["age"].fillna(df["age"].median(), inplace=True)
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,True,C,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,False,C,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,True,C,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,True,C,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,False,B,Southampton,yes,True
888,0,3,female,28.0,1,2,23.4500,S,Third,False,C,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,True,C,Queenstown,no,True

In [102]:
df.groupby(["pclass","sex"]).agg({
    "survived":["sum","mean","sum"]
    })

              survived
                   sum      mean sum
pclass sex
1      female       91  0.968085  91
       male         45  0.368852  45
2      female       70  0.921053  70
       male         17  0.157407  17
3      female       72  0.500000  72
       male         47  0.135447  47

In [110]:
def age_flag(age):
    if age<30:
        return 1
    else:
        return 0

df["age_flag"]=df["age"].apply(lambda x:age_flag(x)).head()

### or

#df["age_flag"]=df["age"].apply(age_flag).head()

In [112]:
df = sns.load_dataset("tips")
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [115]:
df.groupby(["time"]).agg({  "total_bill":["min","max","mean","sum"]    })

<ipython-input-115-2f192ed7452c>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["day","time"]).agg({  "total_bill":["min","max","mean","sum"]    })

            total_bill
                   min    max       mean      sum
day  time
Thur Lunch        7.51  43.11  17.664754  1077.55
     Dinner      18.78  18.78  18.780000    18.78
Fri  Lunch        8.58  16.27  12.845714    89.92
     Dinner       5.75  40.17  19.663333   235.96
Sat  Lunch         NaN    NaN        NaN     0.00
     Dinner       3.07  50.81  20.441379  1778.40
Sun  Lunch         NaN    NaN        NaN     0.00
     Dinner       7.25  48.17  21.410000  1627.16

In [116]:
df.groupby(["day","time"]).agg({  "total_bill":["min","max","mean","sum"]    })

<ipython-input-116-2f192ed7452c>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["day","time"]).agg({  "total_bill":["min","max","mean","sum"]    })

            total_bill
                   min    max       mean      sum
day  time
Thur Lunch        7.51  43.11  17.664754  1077.55
     Dinner      18.78  18.78  18.780000    18.78
Fri  Lunch        8.58  16.27  12.845714    89.92
     Dinner       5.75  40.17  19.663333   235.96
Sat  Lunch         NaN    NaN        NaN     0.00
     Dinner       3.07  50.81  20.441379  1778.40
Sun  Lunch         NaN    NaN        NaN     0.00
     Dinner       7.25  48.17  21.410000  1627.16

In [119]:
df[(df["time"]=="Lunch")&(df["sex"]=="Female")].groupby(["day"]).agg({
    "total_bill":["min","max","mean","sum"],
    "tip":["min","max","mean","sum"]
    })

<ipython-input-119-76274b06b97f>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[(df["time"]=="Lunch")&(df["sex"]=="Female")].groupby(["day"]).agg({

     total_bill                            tip
            min    max      mean     sum   min   max      mean    sum
day
Thur       8.35  43.11  16.64871  516.11  1.25  5.17  2.561935  79.42
Fri       10.09  16.27  13.94000   55.76  2.00  3.48  2.745000  10.98
Sat         NaN    NaN       NaN    0.00   NaN   NaN       NaN   0.00
Sun         NaN    NaN       NaN    0.00   NaN   NaN       NaN   0.00

In [120]:
df.loc[(df["size"]<3) & (df["total_bill"]>10), "total_bill"].mean()

17.184965034965035

In [126]:
total_bill_tip_sum=df["total_bill"]+df["tip"]
total_bill_tip_sum

0      18.00
1      12.00
2      24.51
3      26.99
4      28.20
       ...
239    34.95
240    29.18
241    24.67
242    19.57
243    21.78
Length: 244, dtype: float64

In [132]:
new_df=df.sort_values("total_bill_tip_sum", ascending=False)[:30]
new_df.shape

(30, 8)